import { storeageVideo } from '~/asset/video';

export const postOfPerson = [
    {
        id: 1,
        to: '/@duyen',
        avatar: 'https://img.meta.com.vn/Data/image/2021/09/22/anh-meo-cute-de-thuong-dang-yeu-44.jpg',
        userName: 'duyenkendy_official',
        nickName: 'Duyên Kendy',
        video: storeageVideo.abc,
        width: 576,
        height: 1024,
        description: 'Nếu bạn muốn vai to nam tính thì áp dụng các bài vai nay',
        hashTag: ['#gym', '#hihi'],
        originMusic: 'owner',
        like: '123k',
        comment: '10k',
        share: '20k',
    },
    {
        id: 2,
        to: '/@hoa',
        avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD4Q0sDPKdoArvNRBrtaaxhNvYya_sLpG9LmlNMrj-mg&s',
        userName: 'duongtamca',
        nickName: 'Đường Tam Ca',
        video: storeageVideo.thuy_trieu_len_cao,
        width: 576,
        height: 1024,
        description: 'Nếu bạn muốn vai to nam tính thì áp dụng các bài vai nay',
        hashTag: ['#gym'],
        originMusic: 'owner',
        like: '123k',
        comment: '10k',
        share: '20k',
    },
    {
        id: 3,
        to: '/@zzz',
        avatar: 'https://img.meta.com.vn/Data/image/2021/09/20/anh-meo-che-anh-meo-bua-18.jpg',
        userName: 'hoaa.hanassii',
        nickName: 'Đào Lê Phương Hoa',
        video: storeageVideo.thuyen_quyen,
        width: 576,
        height: 1024,
        description: 'Nếu bạn muốn vai to nam tính thì áp dụng các bài vai nay',
        hashTag: ['#gym'],
        originMusic: 'owner',
        like: '123k',
        comment: '10k',
        share: '20k',
    },
    {
        id: 4,
        to: '/@hoa',
        avatar: 'https://i.pinimg.com/564x/05/09/94/050994962c61328795f2568b4c51c0ab.jpg',
        userName: 'nhachay1091',
        nickName: 'Nhạc Remix',
        video: storeageVideo.thuyen_quyen,
        width: 576,
        height: 1024,
        description: 'Pháo Hồng remix',
        hashTag: ['#pháo hồng'],
        originMusic: 'owner zz',
        like: '123k',
        comment: '10k',
        share: '20k',
    },
    {
        id: 5,
        to: '/@hoa',
        avatar: 'https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2020/8/21/829850/Bat-Cuoi-Truoc-Nhung-07.jpg',
        userName: 'Azaki',
        nickName: 'Tiêu Viêm',
        video: storeageVideo.videoTo,
        width: 1024,
        height: 576,
        description: 'Hoa điêu thuyền remix',
        hashTag: ['#hoadieuthuyen'],
        originMusic: 'Hoa Điêu Thuyền',
        like: '123k',
        comment: '10k',
        share: '20k',
    },
];
